name: deeplink_x
description: Easy to use Flutter plugin for type-safe external deeplink launching with built-in smart fallback, supporting app stores and popular apps.
version: 1.0.4

repository: https://github.com/DeepLinkX/DeeplinkX
issue_tracker: https://github.com/DeepLinkX/DeeplinkX/issues
documentation: https://pub.dev/documentation/deeplink_x/latest/deeplink_x/

topics:
  - app-links
  - external-deeplink
  - universal-links
  - custom-url-schemes
  - open-store

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter
  deeplink_x_platform_interface: ^0.1.0
  deeplink_x_android: ^0.1.0
  deeplink_x_ios: ^0.1.0
  deeplink_x_linux: ^0.1.0
  deeplink_x_macos: ^0.1.0
  deeplink_x_web: ^0.1.0
  deeplink_x_windows: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.7

flutter:
  plugin:
    platforms:
      android:
        default_package: deeplink_x_android
      ios:
        default_package: deeplink_x_ios
      linux:
        default_package: deeplink_x_linux
      macos:
        default_package: deeplink_x_macos
      web:
        default_package: deeplink_x_web
      windows:
        default_package: deeplink_x_windows
