name: deeplink_x
description: Lightweight Flutter plugin for type-safe external deeplink launching across platforms with built-in web fallback.
version: 0.0.3

repository: https://github.com/ParhamHatan/DeeplinkX
issue_tracker: https://github.com/ParhamHatan/DeeplinkX/issues
documentation: https://pub.dev/documentation/deeplink_x/latest/deeplink_x/

topics:
  - deeplink
  - external-deeplink
  - custom-url-schemes

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
