name: deeplink_x
description: A cross-platform deeplink plugin that supports various apps and platforms
version: 0.0.1
homepage: https://github.com/ParhamHatan/DeeplinkX
repository: https://github.com/ParhamHatan/DeeplinkX
issue_tracker: https://github.com/ParhamHatan/DeeplinkX/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  url_launcher_platform_interface: ^2.3.2

flutter:
  plugin:
    platforms: {}