name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  verify-tag-on-master:
    uses: ./.github/workflows/verify-tag.yml

  publish:
    needs: verify-tag-on-master
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
    with:
      environment: pub.dev
